name: air_home_stay
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.10
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  cloud_firestore: ^4.8.4
  provider: ^6.0.5
  firebase_database: ^10.2.4
  flutter_spinkit: ^5.1.0
  flutter_map: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/first.jpg
    - assets/second.jpg
    - assets/third.jpg
    - assets/signup_image.png
    - assets/login_image.png
    - assets/room1.jpg
    - assets/room2.jpg
    - assets/room3.jpg
    - assets/room4.jpg
    - assets/room5.jpg
    - assets/room6.jpg
    - android/app/src/main/res/mipmap-hdpi/ic_launcher.png
    - android/app/src/main/res/mipmap-mdpi/ic_launcher.png
    - android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
    - android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
    - android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
